swagger: '2.0'
info:
  version: "1.0.0"
  title: School-API
host: api.yanqun.com
basePath: /yq
paths:
  /school:
    post:
      summary: 新增学校
      parameters:
        -
          name: body
          in: body
          description: 学校实体类
          required: true
          schema:
            $ref: '#/definitions/School'
      responses:
        200:
          description: 成功响应
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: 返回学校列表
      responses:
        200:
          description: 成功响应
          schema:
            $ref: '#/definitions/ApiSchoolListResponse'      
  /school/{schoolId}:
    put:
      summary: 修改学校
      parameters:
        - name: schoolId
          in: path
          description: 学校ID
          required: true
          type: string
        - name: body
          in: body
          description: 学校实体类
          required: true
          schema:
            $ref: '#/definitions/School'
      responses:
        200:
          description: 成功响应
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 删除学校
      parameters:
        - name: schoolId
          in: path
          description: 学校ID
          required: true
          type: string      
      responses:
        200:
          description: 成功响应
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: 根据ID查询学校
      parameters:
        - name: schoolId
          in: path
          description: 学校ID
          required: true
          type: string  
      responses:
        200:
          description: 成功响应
          schema:
            $ref: '#/definitions/ApiSchoolResponse'
  /school/search:
    post:
      summary: 根据条件查询学校列表 
      parameters:
        - name: body
          in: body
          description: 学校实体类
          required: true
          schema:
            $ref: '#/definitions/School'
      responses:
        200:
          description: 成功响应
          schema:
            $ref: '#/definitions/ApiSchoolListResponse'
  /school/search/{page}/{size}:
    post:
      summary: 根据条件查询学校列表 
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32          
        - name: body
          in: body
          description: 学校实体类
          required: true
          schema:
            $ref: '#/definitions/School'
      responses:
        200:
          description: 成功响应
          schema:
            $ref: '#/definitions/ApiSchoolPageResponse'    
definitions:
  School: 
    type: object
    properties:
      id:
        type: string
        description: ID
      name:
        type: string
        description: 学校名称
      isPopular:
        type: string
        description: 是否热门 
  ApiResponse:
    type: object
    properties:
      flag:
        type: boolean
        description: 是否成功
      code:
        type: integer
        format: int32
        description: 返回码
      message:
        type: string
        description: 返回信息
  ApiSchoolResponse:
    type: object
    properties:
      flag:
        type: boolean
        description: 是否成功
      code:
        type: integer
        format: int32
        description: 返回码
      message:
        type: string
        description: 返回信息
      data:
        $ref: '#/definitions/School'
  SchoolList:
    type: array
    items: 
        $ref: '#/definitions/School'
  ApiSchoolListResponse:
    type: object
    properties:
      flag:
        type: boolean
        description: 是否成功
      code:
        type: integer
        format: int32
        description: 返回码
      message:
        type: string
        description: 返回信息
      data:
        $ref: '#/definitions/SchoolList' 
  ApiSchoolPageResponse:
    type: object
    properties:
      flag:
        type: boolean
        description: 是否成功
      code:
        type: integer
        format: int32
        description: 返回码
      message:
        type: string
        description: 返回信息
      data:
        properties:
          total:
            type: integer
            format: int32
          rows:
            $ref: '#/definitions/SchoolList' 