// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/yanqun/protobuf/diff/MyMessage.proto

package com.yanqun.protobuf.diff;

public final class MyMessage {
  private MyMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yanqun.protobuf.diff.MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.yanqun.protobuf.diff.MessageData.MessageType Message_Type = 1;</code>
     */
    boolean hasMessageType();
    /**
     * <code>required .com.yanqun.protobuf.diff.MessageData.MessageType Message_Type = 1;</code>
     */
    com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType getMessageType();

    /**
     * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
     */
    boolean hasPerson();
    /**
     * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
     */
    com.yanqun.protobuf.diff.MyMessage.PersonData getPerson();
    /**
     * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
     */
    com.yanqun.protobuf.diff.MyMessage.PersonDataOrBuilder getPersonOrBuilder();

    /**
     * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
     */
    boolean hasDog();
    /**
     * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
     */
    com.yanqun.protobuf.diff.MyMessage.DogData getDog();
    /**
     * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
     */
    com.yanqun.protobuf.diff.MyMessage.DogDataOrBuilder getDogOrBuilder();

    public com.yanqun.protobuf.diff.MyMessage.MessageData.MessageContentCase getMessageContentCase();
  }
  /**
   * Protobuf type {@code com.yanqun.protobuf.diff.MessageData}
   */
  public  static final class MessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yanqun.protobuf.diff.MessageData)
      MessageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageData() {
      messageType_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType value = com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.yanqun.protobuf.diff.MyMessage.PersonData.Builder subBuilder = null;
              if (messageContentCase_ == 2) {
                subBuilder = ((com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_).toBuilder();
              }
              messageContent_ =
                  input.readMessage(com.yanqun.protobuf.diff.MyMessage.PersonData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_);
                messageContent_ = subBuilder.buildPartial();
              }
              messageContentCase_ = 2;
              break;
            }
            case 26: {
              com.yanqun.protobuf.diff.MyMessage.DogData.Builder subBuilder = null;
              if (messageContentCase_ == 3) {
                subBuilder = ((com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_).toBuilder();
              }
              messageContent_ =
                  input.readMessage(com.yanqun.protobuf.diff.MyMessage.DogData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_);
                messageContent_ = subBuilder.buildPartial();
              }
              messageContentCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_MessageData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yanqun.protobuf.diff.MyMessage.MessageData.class, com.yanqun.protobuf.diff.MyMessage.MessageData.Builder.class);
    }

    /**
     * Protobuf enum {@code com.yanqun.protobuf.diff.MessageData.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PersonType = 1;</code>
       */
      PersonType(1),
      /**
       * <code>DogType = 2;</code>
       */
      DogType(2),
      ;

      /**
       * <code>PersonType = 1;</code>
       */
      public static final int PersonType_VALUE = 1;
      /**
       * <code>DogType = 2;</code>
       */
      public static final int DogType_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 1: return PersonType;
          case 2: return DogType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yanqun.protobuf.diff.MyMessage.MessageData.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.yanqun.protobuf.diff.MessageData.MessageType)
    }

    private int bitField0_;
    private int messageContentCase_ = 0;
    private java.lang.Object messageContent_;
    public enum MessageContentCase
        implements com.google.protobuf.Internal.EnumLite {
      PERSON(2),
      DOG(3),
      MESSAGECONTENT_NOT_SET(0);
      private final int value;
      private MessageContentCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageContentCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageContentCase forNumber(int value) {
        switch (value) {
          case 2: return PERSON;
          case 3: return DOG;
          case 0: return MESSAGECONTENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageContentCase
    getMessageContentCase() {
      return MessageContentCase.forNumber(
          messageContentCase_);
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>required .com.yanqun.protobuf.diff.MessageData.MessageType Message_Type = 1;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.yanqun.protobuf.diff.MessageData.MessageType Message_Type = 1;</code>
     */
    public com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType result = com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType.valueOf(messageType_);
      return result == null ? com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType.PersonType : result;
    }

    public static final int PERSON_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
     */
    public boolean hasPerson() {
      return messageContentCase_ == 2;
    }
    /**
     * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
     */
    public com.yanqun.protobuf.diff.MyMessage.PersonData getPerson() {
      if (messageContentCase_ == 2) {
         return (com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_;
      }
      return com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance();
    }
    /**
     * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
     */
    public com.yanqun.protobuf.diff.MyMessage.PersonDataOrBuilder getPersonOrBuilder() {
      if (messageContentCase_ == 2) {
         return (com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_;
      }
      return com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance();
    }

    public static final int DOG_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
     */
    public boolean hasDog() {
      return messageContentCase_ == 3;
    }
    /**
     * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
     */
    public com.yanqun.protobuf.diff.MyMessage.DogData getDog() {
      if (messageContentCase_ == 3) {
         return (com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_;
      }
      return com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance();
    }
    /**
     * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
     */
    public com.yanqun.protobuf.diff.MyMessage.DogDataOrBuilder getDogOrBuilder() {
      if (messageContentCase_ == 3) {
         return (com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_;
      }
      return com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_);
      }
      if (messageContentCase_ == 2) {
        output.writeMessage(2, (com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_);
      }
      if (messageContentCase_ == 3) {
        output.writeMessage(3, (com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (messageContentCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_);
      }
      if (messageContentCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yanqun.protobuf.diff.MyMessage.MessageData)) {
        return super.equals(obj);
      }
      com.yanqun.protobuf.diff.MyMessage.MessageData other = (com.yanqun.protobuf.diff.MyMessage.MessageData) obj;

      boolean result = true;
      result = result && (hasMessageType() == other.hasMessageType());
      if (hasMessageType()) {
        result = result && messageType_ == other.messageType_;
      }
      result = result && getMessageContentCase().equals(
          other.getMessageContentCase());
      if (!result) return false;
      switch (messageContentCase_) {
        case 2:
          result = result && getPerson()
              .equals(other.getPerson());
          break;
        case 3:
          result = result && getDog()
              .equals(other.getDog());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageType()) {
        hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + messageType_;
      }
      switch (messageContentCase_) {
        case 2:
          hash = (37 * hash) + PERSON_FIELD_NUMBER;
          hash = (53 * hash) + getPerson().hashCode();
          break;
        case 3:
          hash = (37 * hash) + DOG_FIELD_NUMBER;
          hash = (53 * hash) + getDog().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yanqun.protobuf.diff.MyMessage.MessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yanqun.protobuf.diff.MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yanqun.protobuf.diff.MessageData)
        com.yanqun.protobuf.diff.MyMessage.MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_MessageData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yanqun.protobuf.diff.MyMessage.MessageData.class, com.yanqun.protobuf.diff.MyMessage.MessageData.Builder.class);
      }

      // Construct using com.yanqun.protobuf.diff.MyMessage.MessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageContentCase_ = 0;
        messageContent_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_MessageData_descriptor;
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.MessageData getDefaultInstanceForType() {
        return com.yanqun.protobuf.diff.MyMessage.MessageData.getDefaultInstance();
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.MessageData build() {
        com.yanqun.protobuf.diff.MyMessage.MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.MessageData buildPartial() {
        com.yanqun.protobuf.diff.MyMessage.MessageData result = new com.yanqun.protobuf.diff.MyMessage.MessageData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (messageContentCase_ == 2) {
          if (personBuilder_ == null) {
            result.messageContent_ = messageContent_;
          } else {
            result.messageContent_ = personBuilder_.build();
          }
        }
        if (messageContentCase_ == 3) {
          if (dogBuilder_ == null) {
            result.messageContent_ = messageContent_;
          } else {
            result.messageContent_ = dogBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.messageContentCase_ = messageContentCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yanqun.protobuf.diff.MyMessage.MessageData) {
          return mergeFrom((com.yanqun.protobuf.diff.MyMessage.MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yanqun.protobuf.diff.MyMessage.MessageData other) {
        if (other == com.yanqun.protobuf.diff.MyMessage.MessageData.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        switch (other.getMessageContentCase()) {
          case PERSON: {
            mergePerson(other.getPerson());
            break;
          }
          case DOG: {
            mergeDog(other.getDog());
            break;
          }
          case MESSAGECONTENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMessageType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yanqun.protobuf.diff.MyMessage.MessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yanqun.protobuf.diff.MyMessage.MessageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageContentCase_ = 0;
      private java.lang.Object messageContent_;
      public MessageContentCase
          getMessageContentCase() {
        return MessageContentCase.forNumber(
            messageContentCase_);
      }

      public Builder clearMessageContent() {
        messageContentCase_ = 0;
        messageContent_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int messageType_ = 1;
      /**
       * <code>required .com.yanqun.protobuf.diff.MessageData.MessageType Message_Type = 1;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.yanqun.protobuf.diff.MessageData.MessageType Message_Type = 1;</code>
       */
      public com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType result = com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType.valueOf(messageType_);
        return result == null ? com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType.PersonType : result;
      }
      /**
       * <code>required .com.yanqun.protobuf.diff.MessageData.MessageType Message_Type = 1;</code>
       */
      public Builder setMessageType(com.yanqun.protobuf.diff.MyMessage.MessageData.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.yanqun.protobuf.diff.MessageData.MessageType Message_Type = 1;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.yanqun.protobuf.diff.MyMessage.PersonData, com.yanqun.protobuf.diff.MyMessage.PersonData.Builder, com.yanqun.protobuf.diff.MyMessage.PersonDataOrBuilder> personBuilder_;
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      public boolean hasPerson() {
        return messageContentCase_ == 2;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      public com.yanqun.protobuf.diff.MyMessage.PersonData getPerson() {
        if (personBuilder_ == null) {
          if (messageContentCase_ == 2) {
            return (com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_;
          }
          return com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance();
        } else {
          if (messageContentCase_ == 2) {
            return personBuilder_.getMessage();
          }
          return com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      public Builder setPerson(com.yanqun.protobuf.diff.MyMessage.PersonData value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageContent_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        messageContentCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      public Builder setPerson(
          com.yanqun.protobuf.diff.MyMessage.PersonData.Builder builderForValue) {
        if (personBuilder_ == null) {
          messageContent_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        messageContentCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      public Builder mergePerson(com.yanqun.protobuf.diff.MyMessage.PersonData value) {
        if (personBuilder_ == null) {
          if (messageContentCase_ == 2 &&
              messageContent_ != com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance()) {
            messageContent_ = com.yanqun.protobuf.diff.MyMessage.PersonData.newBuilder((com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_)
                .mergeFrom(value).buildPartial();
          } else {
            messageContent_ = value;
          }
          onChanged();
        } else {
          if (messageContentCase_ == 2) {
            personBuilder_.mergeFrom(value);
          }
          personBuilder_.setMessage(value);
        }
        messageContentCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          if (messageContentCase_ == 2) {
            messageContentCase_ = 0;
            messageContent_ = null;
            onChanged();
          }
        } else {
          if (messageContentCase_ == 2) {
            messageContentCase_ = 0;
            messageContent_ = null;
          }
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      public com.yanqun.protobuf.diff.MyMessage.PersonData.Builder getPersonBuilder() {
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      public com.yanqun.protobuf.diff.MyMessage.PersonDataOrBuilder getPersonOrBuilder() {
        if ((messageContentCase_ == 2) && (personBuilder_ != null)) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          if (messageContentCase_ == 2) {
            return (com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_;
          }
          return com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.PersonData person = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yanqun.protobuf.diff.MyMessage.PersonData, com.yanqun.protobuf.diff.MyMessage.PersonData.Builder, com.yanqun.protobuf.diff.MyMessage.PersonDataOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          if (!(messageContentCase_ == 2)) {
            messageContent_ = com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance();
          }
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yanqun.protobuf.diff.MyMessage.PersonData, com.yanqun.protobuf.diff.MyMessage.PersonData.Builder, com.yanqun.protobuf.diff.MyMessage.PersonDataOrBuilder>(
                  (com.yanqun.protobuf.diff.MyMessage.PersonData) messageContent_,
                  getParentForChildren(),
                  isClean());
          messageContent_ = null;
        }
        messageContentCase_ = 2;
        onChanged();;
        return personBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.yanqun.protobuf.diff.MyMessage.DogData, com.yanqun.protobuf.diff.MyMessage.DogData.Builder, com.yanqun.protobuf.diff.MyMessage.DogDataOrBuilder> dogBuilder_;
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      public boolean hasDog() {
        return messageContentCase_ == 3;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      public com.yanqun.protobuf.diff.MyMessage.DogData getDog() {
        if (dogBuilder_ == null) {
          if (messageContentCase_ == 3) {
            return (com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_;
          }
          return com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance();
        } else {
          if (messageContentCase_ == 3) {
            return dogBuilder_.getMessage();
          }
          return com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      public Builder setDog(com.yanqun.protobuf.diff.MyMessage.DogData value) {
        if (dogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageContent_ = value;
          onChanged();
        } else {
          dogBuilder_.setMessage(value);
        }
        messageContentCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      public Builder setDog(
          com.yanqun.protobuf.diff.MyMessage.DogData.Builder builderForValue) {
        if (dogBuilder_ == null) {
          messageContent_ = builderForValue.build();
          onChanged();
        } else {
          dogBuilder_.setMessage(builderForValue.build());
        }
        messageContentCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      public Builder mergeDog(com.yanqun.protobuf.diff.MyMessage.DogData value) {
        if (dogBuilder_ == null) {
          if (messageContentCase_ == 3 &&
              messageContent_ != com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance()) {
            messageContent_ = com.yanqun.protobuf.diff.MyMessage.DogData.newBuilder((com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_)
                .mergeFrom(value).buildPartial();
          } else {
            messageContent_ = value;
          }
          onChanged();
        } else {
          if (messageContentCase_ == 3) {
            dogBuilder_.mergeFrom(value);
          }
          dogBuilder_.setMessage(value);
        }
        messageContentCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      public Builder clearDog() {
        if (dogBuilder_ == null) {
          if (messageContentCase_ == 3) {
            messageContentCase_ = 0;
            messageContent_ = null;
            onChanged();
          }
        } else {
          if (messageContentCase_ == 3) {
            messageContentCase_ = 0;
            messageContent_ = null;
          }
          dogBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      public com.yanqun.protobuf.diff.MyMessage.DogData.Builder getDogBuilder() {
        return getDogFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      public com.yanqun.protobuf.diff.MyMessage.DogDataOrBuilder getDogOrBuilder() {
        if ((messageContentCase_ == 3) && (dogBuilder_ != null)) {
          return dogBuilder_.getMessageOrBuilder();
        } else {
          if (messageContentCase_ == 3) {
            return (com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_;
          }
          return com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.yanqun.protobuf.diff.DogData dog = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yanqun.protobuf.diff.MyMessage.DogData, com.yanqun.protobuf.diff.MyMessage.DogData.Builder, com.yanqun.protobuf.diff.MyMessage.DogDataOrBuilder> 
          getDogFieldBuilder() {
        if (dogBuilder_ == null) {
          if (!(messageContentCase_ == 3)) {
            messageContent_ = com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance();
          }
          dogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yanqun.protobuf.diff.MyMessage.DogData, com.yanqun.protobuf.diff.MyMessage.DogData.Builder, com.yanqun.protobuf.diff.MyMessage.DogDataOrBuilder>(
                  (com.yanqun.protobuf.diff.MyMessage.DogData) messageContent_,
                  getParentForChildren(),
                  isClean());
          messageContent_ = null;
        }
        messageContentCase_ = 3;
        onChanged();;
        return dogBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yanqun.protobuf.diff.MessageData)
    }

    // @@protoc_insertion_point(class_scope:com.yanqun.protobuf.diff.MessageData)
    private static final com.yanqun.protobuf.diff.MyMessage.MessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yanqun.protobuf.diff.MyMessage.MessageData();
    }

    public static com.yanqun.protobuf.diff.MyMessage.MessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageData>
        PARSER = new com.google.protobuf.AbstractParser<MessageData>() {
      @java.lang.Override
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yanqun.protobuf.diff.MyMessage.MessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yanqun.protobuf.diff.PersonData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string pname = 1;</code>
     */
    boolean hasPname();
    /**
     * <code>optional string pname = 1;</code>
     */
    java.lang.String getPname();
    /**
     * <code>optional string pname = 1;</code>
     */
    com.google.protobuf.ByteString
        getPnameBytes();

    /**
     * <code>optional int32 page = 2;</code>
     */
    boolean hasPage();
    /**
     * <code>optional int32 page = 2;</code>
     */
    int getPage();
  }
  /**
   * Protobuf type {@code com.yanqun.protobuf.diff.PersonData}
   */
  public  static final class PersonData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yanqun.protobuf.diff.PersonData)
      PersonDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PersonData.newBuilder() to construct.
    private PersonData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonData() {
      pname_ = "";
      page_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PersonData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              pname_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              page_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_PersonData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_PersonData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yanqun.protobuf.diff.MyMessage.PersonData.class, com.yanqun.protobuf.diff.MyMessage.PersonData.Builder.class);
    }

    private int bitField0_;
    public static final int PNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object pname_;
    /**
     * <code>optional string pname = 1;</code>
     */
    public boolean hasPname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string pname = 1;</code>
     */
    public java.lang.String getPname() {
      java.lang.Object ref = pname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPnameBytes() {
      java.lang.Object ref = pname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <code>optional int32 page = 2;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, page_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yanqun.protobuf.diff.MyMessage.PersonData)) {
        return super.equals(obj);
      }
      com.yanqun.protobuf.diff.MyMessage.PersonData other = (com.yanqun.protobuf.diff.MyMessage.PersonData) obj;

      boolean result = true;
      result = result && (hasPname() == other.hasPname());
      if (hasPname()) {
        result = result && getPname()
            .equals(other.getPname());
      }
      result = result && (hasPage() == other.hasPage());
      if (hasPage()) {
        result = result && (getPage()
            == other.getPage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPname()) {
        hash = (37 * hash) + PNAME_FIELD_NUMBER;
        hash = (53 * hash) + getPname().hashCode();
      }
      if (hasPage()) {
        hash = (37 * hash) + PAGE_FIELD_NUMBER;
        hash = (53 * hash) + getPage();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.PersonData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yanqun.protobuf.diff.MyMessage.PersonData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yanqun.protobuf.diff.PersonData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yanqun.protobuf.diff.PersonData)
        com.yanqun.protobuf.diff.MyMessage.PersonDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_PersonData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_PersonData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yanqun.protobuf.diff.MyMessage.PersonData.class, com.yanqun.protobuf.diff.MyMessage.PersonData.Builder.class);
      }

      // Construct using com.yanqun.protobuf.diff.MyMessage.PersonData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        page_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_PersonData_descriptor;
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.PersonData getDefaultInstanceForType() {
        return com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance();
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.PersonData build() {
        com.yanqun.protobuf.diff.MyMessage.PersonData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.PersonData buildPartial() {
        com.yanqun.protobuf.diff.MyMessage.PersonData result = new com.yanqun.protobuf.diff.MyMessage.PersonData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pname_ = pname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.page_ = page_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yanqun.protobuf.diff.MyMessage.PersonData) {
          return mergeFrom((com.yanqun.protobuf.diff.MyMessage.PersonData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yanqun.protobuf.diff.MyMessage.PersonData other) {
        if (other == com.yanqun.protobuf.diff.MyMessage.PersonData.getDefaultInstance()) return this;
        if (other.hasPname()) {
          bitField0_ |= 0x00000001;
          pname_ = other.pname_;
          onChanged();
        }
        if (other.hasPage()) {
          setPage(other.getPage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yanqun.protobuf.diff.MyMessage.PersonData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yanqun.protobuf.diff.MyMessage.PersonData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object pname_ = "";
      /**
       * <code>optional string pname = 1;</code>
       */
      public boolean hasPname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string pname = 1;</code>
       */
      public java.lang.String getPname() {
        java.lang.Object ref = pname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPnameBytes() {
        java.lang.Object ref = pname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pname = 1;</code>
       */
      public Builder setPname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pname = 1;</code>
       */
      public Builder clearPname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pname_ = getDefaultInstance().getPname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pname = 1;</code>
       */
      public Builder setPnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pname_ = value;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>optional int32 page = 2;</code>
       */
      public boolean hasPage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 page = 2;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>optional int32 page = 2;</code>
       */
      public Builder setPage(int value) {
        bitField0_ |= 0x00000002;
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page = 2;</code>
       */
      public Builder clearPage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        page_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yanqun.protobuf.diff.PersonData)
    }

    // @@protoc_insertion_point(class_scope:com.yanqun.protobuf.diff.PersonData)
    private static final com.yanqun.protobuf.diff.MyMessage.PersonData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yanqun.protobuf.diff.MyMessage.PersonData();
    }

    public static com.yanqun.protobuf.diff.MyMessage.PersonData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PersonData>
        PARSER = new com.google.protobuf.AbstractParser<PersonData>() {
      @java.lang.Override
      public PersonData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yanqun.protobuf.diff.MyMessage.PersonData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DogDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yanqun.protobuf.diff.DogData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string dname = 1;</code>
     */
    boolean hasDname();
    /**
     * <code>optional string dname = 1;</code>
     */
    java.lang.String getDname();
    /**
     * <code>optional string dname = 1;</code>
     */
    com.google.protobuf.ByteString
        getDnameBytes();

    /**
     * <code>optional string dcolor = 2;</code>
     */
    boolean hasDcolor();
    /**
     * <code>optional string dcolor = 2;</code>
     */
    java.lang.String getDcolor();
    /**
     * <code>optional string dcolor = 2;</code>
     */
    com.google.protobuf.ByteString
        getDcolorBytes();
  }
  /**
   * Protobuf type {@code com.yanqun.protobuf.diff.DogData}
   */
  public  static final class DogData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yanqun.protobuf.diff.DogData)
      DogDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DogData.newBuilder() to construct.
    private DogData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DogData() {
      dname_ = "";
      dcolor_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DogData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              dname_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              dcolor_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_DogData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_DogData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yanqun.protobuf.diff.MyMessage.DogData.class, com.yanqun.protobuf.diff.MyMessage.DogData.Builder.class);
    }

    private int bitField0_;
    public static final int DNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object dname_;
    /**
     * <code>optional string dname = 1;</code>
     */
    public boolean hasDname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string dname = 1;</code>
     */
    public java.lang.String getDname() {
      java.lang.Object ref = dname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDnameBytes() {
      java.lang.Object ref = dname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DCOLOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object dcolor_;
    /**
     * <code>optional string dcolor = 2;</code>
     */
    public boolean hasDcolor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string dcolor = 2;</code>
     */
    public java.lang.String getDcolor() {
      java.lang.Object ref = dcolor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dcolor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dcolor = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDcolorBytes() {
      java.lang.Object ref = dcolor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dcolor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dcolor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dcolor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yanqun.protobuf.diff.MyMessage.DogData)) {
        return super.equals(obj);
      }
      com.yanqun.protobuf.diff.MyMessage.DogData other = (com.yanqun.protobuf.diff.MyMessage.DogData) obj;

      boolean result = true;
      result = result && (hasDname() == other.hasDname());
      if (hasDname()) {
        result = result && getDname()
            .equals(other.getDname());
      }
      result = result && (hasDcolor() == other.hasDcolor());
      if (hasDcolor()) {
        result = result && getDcolor()
            .equals(other.getDcolor());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDname()) {
        hash = (37 * hash) + DNAME_FIELD_NUMBER;
        hash = (53 * hash) + getDname().hashCode();
      }
      if (hasDcolor()) {
        hash = (37 * hash) + DCOLOR_FIELD_NUMBER;
        hash = (53 * hash) + getDcolor().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yanqun.protobuf.diff.MyMessage.DogData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yanqun.protobuf.diff.MyMessage.DogData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yanqun.protobuf.diff.DogData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yanqun.protobuf.diff.DogData)
        com.yanqun.protobuf.diff.MyMessage.DogDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_DogData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_DogData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yanqun.protobuf.diff.MyMessage.DogData.class, com.yanqun.protobuf.diff.MyMessage.DogData.Builder.class);
      }

      // Construct using com.yanqun.protobuf.diff.MyMessage.DogData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dcolor_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yanqun.protobuf.diff.MyMessage.internal_static_com_yanqun_protobuf_diff_DogData_descriptor;
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.DogData getDefaultInstanceForType() {
        return com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance();
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.DogData build() {
        com.yanqun.protobuf.diff.MyMessage.DogData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yanqun.protobuf.diff.MyMessage.DogData buildPartial() {
        com.yanqun.protobuf.diff.MyMessage.DogData result = new com.yanqun.protobuf.diff.MyMessage.DogData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dname_ = dname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dcolor_ = dcolor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yanqun.protobuf.diff.MyMessage.DogData) {
          return mergeFrom((com.yanqun.protobuf.diff.MyMessage.DogData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yanqun.protobuf.diff.MyMessage.DogData other) {
        if (other == com.yanqun.protobuf.diff.MyMessage.DogData.getDefaultInstance()) return this;
        if (other.hasDname()) {
          bitField0_ |= 0x00000001;
          dname_ = other.dname_;
          onChanged();
        }
        if (other.hasDcolor()) {
          bitField0_ |= 0x00000002;
          dcolor_ = other.dcolor_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yanqun.protobuf.diff.MyMessage.DogData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yanqun.protobuf.diff.MyMessage.DogData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object dname_ = "";
      /**
       * <code>optional string dname = 1;</code>
       */
      public boolean hasDname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string dname = 1;</code>
       */
      public java.lang.String getDname() {
        java.lang.Object ref = dname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDnameBytes() {
        java.lang.Object ref = dname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dname = 1;</code>
       */
      public Builder setDname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dname = 1;</code>
       */
      public Builder clearDname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dname_ = getDefaultInstance().getDname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dname = 1;</code>
       */
      public Builder setDnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dcolor_ = "";
      /**
       * <code>optional string dcolor = 2;</code>
       */
      public boolean hasDcolor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string dcolor = 2;</code>
       */
      public java.lang.String getDcolor() {
        java.lang.Object ref = dcolor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dcolor_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dcolor = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDcolorBytes() {
        java.lang.Object ref = dcolor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dcolor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dcolor = 2;</code>
       */
      public Builder setDcolor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dcolor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dcolor = 2;</code>
       */
      public Builder clearDcolor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dcolor_ = getDefaultInstance().getDcolor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dcolor = 2;</code>
       */
      public Builder setDcolorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        dcolor_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yanqun.protobuf.diff.DogData)
    }

    // @@protoc_insertion_point(class_scope:com.yanqun.protobuf.diff.DogData)
    private static final com.yanqun.protobuf.diff.MyMessage.DogData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yanqun.protobuf.diff.MyMessage.DogData();
    }

    public static com.yanqun.protobuf.diff.MyMessage.DogData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DogData>
        PARSER = new com.google.protobuf.AbstractParser<DogData>() {
      @java.lang.Override
      public DogData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DogData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DogData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DogData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yanqun.protobuf.diff.MyMessage.DogData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_protobuf_diff_MessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_protobuf_diff_MessageData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_protobuf_diff_PersonData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_protobuf_diff_PersonData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_protobuf_diff_DogData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_protobuf_diff_DogData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6src/main/java/com/yanqun/protobuf/diff" +
      "/MyMessage.proto\022\030com.yanqun.protobuf.di" +
      "ff\"\376\001\n\013MessageData\022G\n\014Message_Type\030\001 \002(\016" +
      "21.com.yanqun.protobuf.diff.MessageData." +
      "MessageType\0226\n\006person\030\002 \001(\0132$.com.yanqun" +
      ".protobuf.diff.PersonDataH\000\0220\n\003dog\030\003 \001(\013" +
      "2!.com.yanqun.protobuf.diff.DogDataH\000\"*\n" +
      "\013MessageType\022\016\n\nPersonType\020\001\022\013\n\007DogType\020" +
      "\002B\020\n\016messageContent\")\n\nPersonData\022\r\n\005pna" +
      "me\030\001 \001(\t\022\014\n\004page\030\002 \001(\005\"(\n\007DogData\022\r\n\005dna" +
      "me\030\001 \001(\t\022\016\n\006dcolor\030\002 \001(\tB\'\n\030com.yanqun.p" +
      "rotobuf.diffB\tMyMessageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yanqun_protobuf_diff_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yanqun_protobuf_diff_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_protobuf_diff_MessageData_descriptor,
        new java.lang.String[] { "MessageType", "Person", "Dog", "MessageContent", });
    internal_static_com_yanqun_protobuf_diff_PersonData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yanqun_protobuf_diff_PersonData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_protobuf_diff_PersonData_descriptor,
        new java.lang.String[] { "Pname", "Page", });
    internal_static_com_yanqun_protobuf_diff_DogData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_yanqun_protobuf_diff_DogData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_protobuf_diff_DogData_descriptor,
        new java.lang.String[] { "Dname", "Dcolor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
