wx:
  appid: wxb6777fffdf5b64a4
  appsecret: 6b55d3bb4d9c5373c8a30915d900ca13
  tokenurl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${wx.appid}&secret=${wx.appsecret}
  codeurl: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=TOKEN