# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Student_pb2 as Student__pb2


class StudentServiceStub(object):
  """定义接口
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.queryStudentNameById = channel.unary_unary(
        '/com.yanqun.grpc.proto.StudentService/queryStudentNameById',
        request_serializer=Student__pb2.MyRequestId.SerializeToString,
        response_deserializer=Student__pb2.MyResponseName.FromString,
        )
    self.queryStudentsByCourseName = channel.unary_stream(
        '/com.yanqun.grpc.proto.StudentService/queryStudentsByCourseName',
        request_serializer=Student__pb2.MyRequestCourseName.SerializeToString,
        response_deserializer=Student__pb2.MyResponseStudentsStream.FromString,
        )
    self.queryStudentsByCourseName2 = channel.stream_unary(
        '/com.yanqun.grpc.proto.StudentService/queryStudentsByCourseName2',
        request_serializer=Student__pb2.MyRequestCourseName.SerializeToString,
        response_deserializer=Student__pb2.MyResponseStudents.FromString,
        )
    self.queryStudentNameById2 = channel.stream_stream(
        '/com.yanqun.grpc.proto.StudentService/queryStudentNameById2',
        request_serializer=Student__pb2.MyRequestId.SerializeToString,
        response_deserializer=Student__pb2.MyResponseName.FromString,
        )


class StudentServiceServicer(object):
  """定义接口
  """

  def queryStudentNameById(self, request, context):
    """请求一个Requset对象，响应一个Response对象
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryStudentsByCourseName(self, request, context):
    """请求一个Requset对象，响应一个Stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryStudentsByCourseName2(self, request_iterator, context):
    """请求一个Stream，响应一个StreamObserver类型的Response对象
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryStudentNameById2(self, request_iterator, context):
    """请求一个Stream，响应一个Stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StudentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'queryStudentNameById': grpc.unary_unary_rpc_method_handler(
          servicer.queryStudentNameById,
          request_deserializer=Student__pb2.MyRequestId.FromString,
          response_serializer=Student__pb2.MyResponseName.SerializeToString,
      ),
      'queryStudentsByCourseName': grpc.unary_stream_rpc_method_handler(
          servicer.queryStudentsByCourseName,
          request_deserializer=Student__pb2.MyRequestCourseName.FromString,
          response_serializer=Student__pb2.MyResponseStudentsStream.SerializeToString,
      ),
      'queryStudentsByCourseName2': grpc.stream_unary_rpc_method_handler(
          servicer.queryStudentsByCourseName2,
          request_deserializer=Student__pb2.MyRequestCourseName.FromString,
          response_serializer=Student__pb2.MyResponseStudents.SerializeToString,
      ),
      'queryStudentNameById2': grpc.stream_stream_rpc_method_handler(
          servicer.queryStudentNameById2,
          request_deserializer=Student__pb2.MyRequestId.FromString,
          response_serializer=Student__pb2.MyResponseName.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.yanqun.grpc.proto.StudentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
