# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Student.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='Student.proto',
    package='com.yanqun.grpc.proto',
    syntax='proto3',
    serialized_options=_b('\n\025com.yanqun.grpc.protoB\013StudentDataP\001'),
    serialized_pb=_b(
        '\n\rStudent.proto\x12\x15\x63om.yanqun.grpc.proto\"\x19\n\x0bMyRequestId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1e\n\x0eMyResponseName\x12\x0c\n\x04name\x18\x01 \x01(\t\"9\n\tMyStudent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncourseName\x18\x03 \x01(\t\"H\n\x12MyResponseStudents\x12\x32\n\x08students\x18\x01 \x03(\x0b\x32 .com.yanqun.grpc.proto.MyStudent\")\n\x13MyRequestCourseName\x12\x12\n\ncourseName\x18\x01 \x01(\t\"H\n\x18MyResponseStudentsStream\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncourseName\x18\x03 \x01(\t2\xd6\x03\n\x0eStudentService\x12\x63\n\x14queryStudentNameById\x12\".com.yanqun.grpc.proto.MyRequestId\x1a%.com.yanqun.grpc.proto.MyResponseName\"\x00\x12|\n\x19queryStudentsByCourseName\x12*.com.yanqun.grpc.proto.MyRequestCourseName\x1a/.com.yanqun.grpc.proto.MyResponseStudentsStream\"\x00\x30\x01\x12w\n\x1aqueryStudentsByCourseName2\x12*.com.yanqun.grpc.proto.MyRequestCourseName\x1a).com.yanqun.grpc.proto.MyResponseStudents\"\x00(\x01\x12h\n\x15queryStudentNameById2\x12\".com.yanqun.grpc.proto.MyRequestId\x1a%.com.yanqun.grpc.proto.MyResponseName\"\x00(\x01\x30\x01\x42&\n\x15\x63om.yanqun.grpc.protoB\x0bStudentDataP\x01\x62\x06proto3')
)

_MYREQUESTID = _descriptor.Descriptor(
    name='MyRequestId',
    full_name='com.yanqun.grpc.proto.MyRequestId',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='com.yanqun.grpc.proto.MyRequestId.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=40,
    serialized_end=65,
)

_MYRESPONSENAME = _descriptor.Descriptor(
    name='MyResponseName',
    full_name='com.yanqun.grpc.proto.MyResponseName',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='com.yanqun.grpc.proto.MyResponseName.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=67,
    serialized_end=97,
)

_MYSTUDENT = _descriptor.Descriptor(
    name='MyStudent',
    full_name='com.yanqun.grpc.proto.MyStudent',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='com.yanqun.grpc.proto.MyStudent.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='name', full_name='com.yanqun.grpc.proto.MyStudent.name', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='courseName', full_name='com.yanqun.grpc.proto.MyStudent.courseName', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=99,
    serialized_end=156,
)

_MYRESPONSESTUDENTS = _descriptor.Descriptor(
    name='MyResponseStudents',
    full_name='com.yanqun.grpc.proto.MyResponseStudents',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='students', full_name='com.yanqun.grpc.proto.MyResponseStudents.students', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=158,
    serialized_end=230,
)

_MYREQUESTCOURSENAME = _descriptor.Descriptor(
    name='MyRequestCourseName',
    full_name='com.yanqun.grpc.proto.MyRequestCourseName',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='courseName', full_name='com.yanqun.grpc.proto.MyRequestCourseName.courseName', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=232,
    serialized_end=273,
)

_MYRESPONSESTUDENTSSTREAM = _descriptor.Descriptor(
    name='MyResponseStudentsStream',
    full_name='com.yanqun.grpc.proto.MyResponseStudentsStream',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='com.yanqun.grpc.proto.MyResponseStudentsStream.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='name', full_name='com.yanqun.grpc.proto.MyResponseStudentsStream.name', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='courseName', full_name='com.yanqun.grpc.proto.MyResponseStudentsStream.courseName', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=275,
    serialized_end=347,
)

_MYRESPONSESTUDENTS.fields_by_name['students'].message_type = _MYSTUDENT
DESCRIPTOR.message_types_by_name['MyRequestId'] = _MYREQUESTID
DESCRIPTOR.message_types_by_name['MyResponseName'] = _MYRESPONSENAME
DESCRIPTOR.message_types_by_name['MyStudent'] = _MYSTUDENT
DESCRIPTOR.message_types_by_name['MyResponseStudents'] = _MYRESPONSESTUDENTS
DESCRIPTOR.message_types_by_name['MyRequestCourseName'] = _MYREQUESTCOURSENAME
DESCRIPTOR.message_types_by_name['MyResponseStudentsStream'] = _MYRESPONSESTUDENTSSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyRequestId = _reflection.GeneratedProtocolMessageType('MyRequestId', (_message.Message,), dict(
    DESCRIPTOR=_MYREQUESTID,
    __module__='Student_pb2'
    # @@protoc_insertion_point(class_scope:com.yanqun.grpc.proto.MyRequestId)
))
_sym_db.RegisterMessage(MyRequestId)

MyResponseName = _reflection.GeneratedProtocolMessageType('MyResponseName', (_message.Message,), dict(
    DESCRIPTOR=_MYRESPONSENAME,
    __module__='Student_pb2'
    # @@protoc_insertion_point(class_scope:com.yanqun.grpc.proto.MyResponseName)
))
_sym_db.RegisterMessage(MyResponseName)

MyStudent = _reflection.GeneratedProtocolMessageType('MyStudent', (_message.Message,), dict(
    DESCRIPTOR=_MYSTUDENT,
    __module__='Student_pb2'
    # @@protoc_insertion_point(class_scope:com.yanqun.grpc.proto.MyStudent)
))
_sym_db.RegisterMessage(MyStudent)

MyResponseStudents = _reflection.GeneratedProtocolMessageType('MyResponseStudents', (_message.Message,), dict(
    DESCRIPTOR=_MYRESPONSESTUDENTS,
    __module__='Student_pb2'
    # @@protoc_insertion_point(class_scope:com.yanqun.grpc.proto.MyResponseStudents)
))
_sym_db.RegisterMessage(MyResponseStudents)

MyRequestCourseName = _reflection.GeneratedProtocolMessageType('MyRequestCourseName', (_message.Message,), dict(
    DESCRIPTOR=_MYREQUESTCOURSENAME,
    __module__='Student_pb2'
    # @@protoc_insertion_point(class_scope:com.yanqun.grpc.proto.MyRequestCourseName)
))
_sym_db.RegisterMessage(MyRequestCourseName)

MyResponseStudentsStream = _reflection.GeneratedProtocolMessageType('MyResponseStudentsStream', (_message.Message,),
                                                                    dict(
                                                                        DESCRIPTOR=_MYRESPONSESTUDENTSSTREAM,
                                                                        __module__='Student_pb2'
                                                                        # @@protoc_insertion_point(class_scope:com.yanqun.grpc.proto.MyResponseStudentsStream)
                                                                    ))
_sym_db.RegisterMessage(MyResponseStudentsStream)

DESCRIPTOR._options = None

_STUDENTSERVICE = _descriptor.ServiceDescriptor(
    name='StudentService',
    full_name='com.yanqun.grpc.proto.StudentService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=350,
    serialized_end=820,
    methods=[
        _descriptor.MethodDescriptor(
            name='queryStudentNameById',
            full_name='com.yanqun.grpc.proto.StudentService.queryStudentNameById',
            index=0,
            containing_service=None,
            input_type=_MYREQUESTID,
            output_type=_MYRESPONSENAME,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='queryStudentsByCourseName',
            full_name='com.yanqun.grpc.proto.StudentService.queryStudentsByCourseName',
            index=1,
            containing_service=None,
            input_type=_MYREQUESTCOURSENAME,
            output_type=_MYRESPONSESTUDENTSSTREAM,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='queryStudentsByCourseName2',
            full_name='com.yanqun.grpc.proto.StudentService.queryStudentsByCourseName2',
            index=2,
            containing_service=None,
            input_type=_MYREQUESTCOURSENAME,
            output_type=_MYRESPONSESTUDENTS,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='queryStudentNameById2',
            full_name='com.yanqun.grpc.proto.StudentService.queryStudentNameById2',
            index=3,
            containing_service=None,
            input_type=_MYREQUESTID,
            output_type=_MYRESPONSENAME,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_STUDENTSERVICE)

DESCRIPTOR.services_by_name['StudentService'] = _STUDENTSERVICE

# @@protoc_insertion_point(module_scope)
