// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yanqun.grpc.proto;

public interface MyRequestIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yanqun.grpc.proto.MyRequestId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
