// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yanqun.grpc.proto;

public interface MyResponseNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yanqun.grpc.proto.MyResponseName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
