// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yanqun.grpc.proto;

public interface MyRequestCourseNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yanqun.grpc.proto.MyRequestCourseName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string courseName = 1;</code>
   */
  java.lang.String getCourseName();
  /**
   * <code>string courseName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();
}
