// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yanqun.grpc.proto;

/**
 * Protobuf type {@code com.yanqun.grpc.proto.MyResponseStudents}
 */
public  final class MyResponseStudents extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.yanqun.grpc.proto.MyResponseStudents)
    MyResponseStudentsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MyResponseStudents.newBuilder() to construct.
  private MyResponseStudents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MyResponseStudents() {
    students_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MyResponseStudents(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              students_ = new java.util.ArrayList<com.yanqun.grpc.proto.MyStudent>();
              mutable_bitField0_ |= 0x00000001;
            }
            students_.add(
                input.readMessage(com.yanqun.grpc.proto.MyStudent.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        students_ = java.util.Collections.unmodifiableList(students_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yanqun.grpc.proto.StudentData.internal_static_com_yanqun_grpc_proto_MyResponseStudents_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yanqun.grpc.proto.StudentData.internal_static_com_yanqun_grpc_proto_MyResponseStudents_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yanqun.grpc.proto.MyResponseStudents.class, com.yanqun.grpc.proto.MyResponseStudents.Builder.class);
  }

  public static final int STUDENTS_FIELD_NUMBER = 1;
  private java.util.List<com.yanqun.grpc.proto.MyStudent> students_;
  /**
   * <pre>
   *服务端的响应结果是集合类型，因此需要加上repeated
   * </pre>
   *
   * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
   */
  public java.util.List<com.yanqun.grpc.proto.MyStudent> getStudentsList() {
    return students_;
  }
  /**
   * <pre>
   *服务端的响应结果是集合类型，因此需要加上repeated
   * </pre>
   *
   * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
   */
  public java.util.List<? extends com.yanqun.grpc.proto.MyStudentOrBuilder> 
      getStudentsOrBuilderList() {
    return students_;
  }
  /**
   * <pre>
   *服务端的响应结果是集合类型，因此需要加上repeated
   * </pre>
   *
   * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
   */
  public int getStudentsCount() {
    return students_.size();
  }
  /**
   * <pre>
   *服务端的响应结果是集合类型，因此需要加上repeated
   * </pre>
   *
   * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
   */
  public com.yanqun.grpc.proto.MyStudent getStudents(int index) {
    return students_.get(index);
  }
  /**
   * <pre>
   *服务端的响应结果是集合类型，因此需要加上repeated
   * </pre>
   *
   * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
   */
  public com.yanqun.grpc.proto.MyStudentOrBuilder getStudentsOrBuilder(
      int index) {
    return students_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < students_.size(); i++) {
      output.writeMessage(1, students_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < students_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, students_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yanqun.grpc.proto.MyResponseStudents)) {
      return super.equals(obj);
    }
    com.yanqun.grpc.proto.MyResponseStudents other = (com.yanqun.grpc.proto.MyResponseStudents) obj;

    boolean result = true;
    result = result && getStudentsList()
        .equals(other.getStudentsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentsCount() > 0) {
      hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
      hash = (53 * hash) + getStudentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yanqun.grpc.proto.MyResponseStudents parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yanqun.grpc.proto.MyResponseStudents prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.yanqun.grpc.proto.MyResponseStudents}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.yanqun.grpc.proto.MyResponseStudents)
      com.yanqun.grpc.proto.MyResponseStudentsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yanqun.grpc.proto.StudentData.internal_static_com_yanqun_grpc_proto_MyResponseStudents_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yanqun.grpc.proto.StudentData.internal_static_com_yanqun_grpc_proto_MyResponseStudents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yanqun.grpc.proto.MyResponseStudents.class, com.yanqun.grpc.proto.MyResponseStudents.Builder.class);
    }

    // Construct using com.yanqun.grpc.proto.MyResponseStudents.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (studentsBuilder_ == null) {
        students_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        studentsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yanqun.grpc.proto.StudentData.internal_static_com_yanqun_grpc_proto_MyResponseStudents_descriptor;
    }

    public com.yanqun.grpc.proto.MyResponseStudents getDefaultInstanceForType() {
      return com.yanqun.grpc.proto.MyResponseStudents.getDefaultInstance();
    }

    public com.yanqun.grpc.proto.MyResponseStudents build() {
      com.yanqun.grpc.proto.MyResponseStudents result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yanqun.grpc.proto.MyResponseStudents buildPartial() {
      com.yanqun.grpc.proto.MyResponseStudents result = new com.yanqun.grpc.proto.MyResponseStudents(this);
      int from_bitField0_ = bitField0_;
      if (studentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          students_ = java.util.Collections.unmodifiableList(students_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.students_ = students_;
      } else {
        result.students_ = studentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yanqun.grpc.proto.MyResponseStudents) {
        return mergeFrom((com.yanqun.grpc.proto.MyResponseStudents)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yanqun.grpc.proto.MyResponseStudents other) {
      if (other == com.yanqun.grpc.proto.MyResponseStudents.getDefaultInstance()) return this;
      if (studentsBuilder_ == null) {
        if (!other.students_.isEmpty()) {
          if (students_.isEmpty()) {
            students_ = other.students_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentsIsMutable();
            students_.addAll(other.students_);
          }
          onChanged();
        }
      } else {
        if (!other.students_.isEmpty()) {
          if (studentsBuilder_.isEmpty()) {
            studentsBuilder_.dispose();
            studentsBuilder_ = null;
            students_ = other.students_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentsFieldBuilder() : null;
          } else {
            studentsBuilder_.addAllMessages(other.students_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yanqun.grpc.proto.MyResponseStudents parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yanqun.grpc.proto.MyResponseStudents) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.yanqun.grpc.proto.MyStudent> students_ =
      java.util.Collections.emptyList();
    private void ensureStudentsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        students_ = new java.util.ArrayList<com.yanqun.grpc.proto.MyStudent>(students_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yanqun.grpc.proto.MyStudent, com.yanqun.grpc.proto.MyStudent.Builder, com.yanqun.grpc.proto.MyStudentOrBuilder> studentsBuilder_;

    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public java.util.List<com.yanqun.grpc.proto.MyStudent> getStudentsList() {
      if (studentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(students_);
      } else {
        return studentsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public int getStudentsCount() {
      if (studentsBuilder_ == null) {
        return students_.size();
      } else {
        return studentsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public com.yanqun.grpc.proto.MyStudent getStudents(int index) {
      if (studentsBuilder_ == null) {
        return students_.get(index);
      } else {
        return studentsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder setStudents(
        int index, com.yanqun.grpc.proto.MyStudent value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.set(index, value);
        onChanged();
      } else {
        studentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder setStudents(
        int index, com.yanqun.grpc.proto.MyStudent.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder addStudents(com.yanqun.grpc.proto.MyStudent value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.add(value);
        onChanged();
      } else {
        studentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder addStudents(
        int index, com.yanqun.grpc.proto.MyStudent value) {
      if (studentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentsIsMutable();
        students_.add(index, value);
        onChanged();
      } else {
        studentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder addStudents(
        com.yanqun.grpc.proto.MyStudent.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.add(builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder addStudents(
        int index, com.yanqun.grpc.proto.MyStudent.Builder builderForValue) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder addAllStudents(
        java.lang.Iterable<? extends com.yanqun.grpc.proto.MyStudent> values) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, students_);
        onChanged();
      } else {
        studentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder clearStudents() {
      if (studentsBuilder_ == null) {
        students_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public Builder removeStudents(int index) {
      if (studentsBuilder_ == null) {
        ensureStudentsIsMutable();
        students_.remove(index);
        onChanged();
      } else {
        studentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public com.yanqun.grpc.proto.MyStudent.Builder getStudentsBuilder(
        int index) {
      return getStudentsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public com.yanqun.grpc.proto.MyStudentOrBuilder getStudentsOrBuilder(
        int index) {
      if (studentsBuilder_ == null) {
        return students_.get(index);  } else {
        return studentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public java.util.List<? extends com.yanqun.grpc.proto.MyStudentOrBuilder> 
         getStudentsOrBuilderList() {
      if (studentsBuilder_ != null) {
        return studentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(students_);
      }
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public com.yanqun.grpc.proto.MyStudent.Builder addStudentsBuilder() {
      return getStudentsFieldBuilder().addBuilder(
          com.yanqun.grpc.proto.MyStudent.getDefaultInstance());
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public com.yanqun.grpc.proto.MyStudent.Builder addStudentsBuilder(
        int index) {
      return getStudentsFieldBuilder().addBuilder(
          index, com.yanqun.grpc.proto.MyStudent.getDefaultInstance());
    }
    /**
     * <pre>
     *服务端的响应结果是集合类型，因此需要加上repeated
     * </pre>
     *
     * <code>repeated .com.yanqun.grpc.proto.MyStudent students = 1;</code>
     */
    public java.util.List<com.yanqun.grpc.proto.MyStudent.Builder> 
         getStudentsBuilderList() {
      return getStudentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yanqun.grpc.proto.MyStudent, com.yanqun.grpc.proto.MyStudent.Builder, com.yanqun.grpc.proto.MyStudentOrBuilder> 
        getStudentsFieldBuilder() {
      if (studentsBuilder_ == null) {
        studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yanqun.grpc.proto.MyStudent, com.yanqun.grpc.proto.MyStudent.Builder, com.yanqun.grpc.proto.MyStudentOrBuilder>(
                students_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        students_ = null;
      }
      return studentsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.yanqun.grpc.proto.MyResponseStudents)
  }

  // @@protoc_insertion_point(class_scope:com.yanqun.grpc.proto.MyResponseStudents)
  private static final com.yanqun.grpc.proto.MyResponseStudents DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yanqun.grpc.proto.MyResponseStudents();
  }

  public static com.yanqun.grpc.proto.MyResponseStudents getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MyResponseStudents>
      PARSER = new com.google.protobuf.AbstractParser<MyResponseStudents>() {
    public MyResponseStudents parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MyResponseStudents(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MyResponseStudents> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MyResponseStudents> getParserForType() {
    return PARSER;
  }

  public com.yanqun.grpc.proto.MyResponseStudents getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

