// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yanqun.grpc.proto;

public final class StudentData {
  private StudentData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_grpc_proto_MyRequestId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_grpc_proto_MyRequestId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_grpc_proto_MyResponseName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_grpc_proto_MyResponseName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_grpc_proto_MyStudent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_grpc_proto_MyStudent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_grpc_proto_MyResponseStudents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_grpc_proto_MyResponseStudents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_grpc_proto_MyRequestCourseName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_grpc_proto_MyRequestCourseName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yanqun_grpc_proto_MyResponseStudentsStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yanqun_grpc_proto_MyResponseStudentsStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\025com.yanqun.grpc.proto\"\031" +
      "\n\013MyRequestId\022\n\n\002id\030\001 \001(\005\"\036\n\016MyResponseN" +
      "ame\022\014\n\004name\030\001 \001(\t\"9\n\tMyStudent\022\n\n\002id\030\001 \001" +
      "(\005\022\014\n\004name\030\002 \001(\t\022\022\n\ncourseName\030\003 \001(\t\"H\n\022" +
      "MyResponseStudents\0222\n\010students\030\001 \003(\0132 .c" +
      "om.yanqun.grpc.proto.MyStudent\")\n\023MyRequ" +
      "estCourseName\022\022\n\ncourseName\030\001 \001(\t\"H\n\030MyR" +
      "esponseStudentsStream\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\022\022\n\ncourseName\030\003 \001(\t2\326\003\n\016StudentS" +
      "ervice\022c\n\024queryStudentNameById\022\".com.yan" +
      "qun.grpc.proto.MyRequestId\032%.com.yanqun." +
      "grpc.proto.MyResponseName\"\000\022|\n\031queryStud" +
      "entsByCourseName\022*.com.yanqun.grpc.proto" +
      ".MyRequestCourseName\032/.com.yanqun.grpc.p" +
      "roto.MyResponseStudentsStream\"\0000\001\022w\n\032que" +
      "ryStudentsByCourseName2\022*.com.yanqun.grp" +
      "c.proto.MyRequestCourseName\032).com.yanqun" +
      ".grpc.proto.MyResponseStudents\"\000(\001\022h\n\025qu" +
      "eryStudentNameById2\022\".com.yanqun.grpc.pr" +
      "oto.MyRequestId\032%.com.yanqun.grpc.proto." +
      "MyResponseName\"\000(\0010\001B&\n\025com.yanqun.grpc." +
      "protoB\013StudentDataP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yanqun_grpc_proto_MyRequestId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yanqun_grpc_proto_MyRequestId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_grpc_proto_MyRequestId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_yanqun_grpc_proto_MyResponseName_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yanqun_grpc_proto_MyResponseName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_grpc_proto_MyResponseName_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_yanqun_grpc_proto_MyStudent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_yanqun_grpc_proto_MyStudent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_grpc_proto_MyStudent_descriptor,
        new java.lang.String[] { "Id", "Name", "CourseName", });
    internal_static_com_yanqun_grpc_proto_MyResponseStudents_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_yanqun_grpc_proto_MyResponseStudents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_grpc_proto_MyResponseStudents_descriptor,
        new java.lang.String[] { "Students", });
    internal_static_com_yanqun_grpc_proto_MyRequestCourseName_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_yanqun_grpc_proto_MyRequestCourseName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_grpc_proto_MyRequestCourseName_descriptor,
        new java.lang.String[] { "CourseName", });
    internal_static_com_yanqun_grpc_proto_MyResponseStudentsStream_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_yanqun_grpc_proto_MyResponseStudentsStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yanqun_grpc_proto_MyResponseStudentsStream_descriptor,
        new java.lang.String[] { "Id", "Name", "CourseName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
